In [1]:
3 - 2

[1] 1

In [2]:
4^2

[1] 16

In [3]:
sin(4)

[1] -0.7568025

In [4]:
4 == 4

[1] TRUE

In [6]:
(4 ==4 ) && (3 > 12)


[1] FALSE

&&: and

# variable assignment

In [10]:
a <- 3 + 3

In [11]:
print(a)

[1] 6


In [14]:
greetings <- "hello, world!"

In [15]:
print(greetings)

[1] "hello, world!"


In [16]:
some_logic <- TRUE

#some_logic: variable name.

# The Vector

In [20]:
dat <- c(4,5,6,23,2)

In [21]:
print(dat)

[1]  4  5  6 23  2


In [22]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [24]:
print (v)

[1] 1 2 3 5 4 3


In [25]:
my_vec <- rep(0,10)

In [26]:
print(my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [35]:
m <- 1:20

print (m)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20


In [40]:
v3 <- seq(-10, 10, 2)

In [41]:
print (v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [42]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [47]:
u <- seq(-2,2,1)

In [48]:
print (u)

[1] -2 -1  0  1  2


In [53]:
u2 <- c(-2:2)
print (u2)

[1] -2 -1  0  1  2


In [54]:
u1 <- -2:2
print (u1)

[1] -2 -1  0  1  2


In [3]:
v <- rnorm(5)#standard normal distribution
print(v)

[1] -0.2949742 -0.7489822  1.2009870 -2.0085420  0.5899928


In [4]:
v

[1] -0.2949742 -0.7489822  1.2009870 -2.0085420  0.5899928

In [6]:
v[2]

[1] -0.7489822

In [7]:
v[2:5]

[1] -0.7489822  1.2009870 -2.0085420  0.5899928

In [8]:
v[c(1,3)]

[1] -0.2949742  1.2009870

In [9]:
print(v)

[1] -0.2949742 -0.7489822  1.2009870 -2.0085420  0.5899928


In [10]:
v[-3]

[1] -0.2949742 -0.7489822 -2.0085420  0.5899928

# Assignment with Indexing

In [12]:
u <- c(5,6,8,22)

In [13]:
u[1] <- 0

In [14]:
print(u)

[1]  0  6  8 22


In [15]:
u3 <- u[1:3]

In [16]:
print(u3)

[1] 0 6 8


In [23]:
u <- c(10,20,30)

In [24]:
u[1:2] <- 0

In [25]:
print (u)

[1]  0  0 30


In [34]:
v1 <- c(10,20,30,40,50)
v2 <- v1[c(1,3,5)]
v2

[1] 10 30 50

In [35]:
v1 <- c(10,20,30,40,50)
idx <- c(1,3,5)
v2 <- v1[idx]
print (v2)

[1] 10 30 50


In [36]:
v1 <- seq(10,50,10) #from 10 to 50, step by 10
idx <- c(TRUE, FALSE, TRUE, FALSE, TRUE)
v2 <- v1[idx]
print(v2)

[1] 10 30 50


# Vectorization of Operations

In [37]:
v <- c(44,50,56)
v-20

[1] 24 30 36

In [38]:
v/5

[1]  8.8 10.0 11.2

# Useful Operations on Vectors

In [40]:
v <- rnorm(10)

In [41]:
print(v)

 [1] -0.33004082  0.80318634 -0.60607731  0.76957616  0.26010660  0.42523296
 [7]  0.64501457 -0.09299323  0.26727113  0.36322530


In [42]:
n <- length (v)

In [43]:
print (n)

[1] 10


In [44]:
sum(v)

[1] 2.504502

In [45]:
max(v)

[1] 0.8031863

In [46]:
min(v)

[1] -0.6060773

In [47]:
xbar <- mean(v)

In [48]:
print(xbar)

[1] 0.2504502


In [49]:
s <- sd(v)

In [50]:
print(s)

[1] 0.4670113


# The Matrix

In [52]:
x1 <- c(4,5,6)
x2 <- c(44,55,66)

In [56]:
m <- cbind(x1,x2)
print(m)

     x1 x2
[1,]  4 44
[2,]  5 55
[3,]  6 66


In [58]:
m2 <- rbind(x1,x2)
print(m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   44   55   66


In [60]:
a <- matrix(0,nrow = 5,ncol = 3)
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [61]:
dat <- rnorm (15)
b <- matrix("foo", ncol = 3,nrow = 5)
print (b)

     [,1]  [,2]  [,3] 
[1,] "foo" "foo" "foo"
[2,] "foo" "foo" "foo"
[3,] "foo" "foo" "foo"
[4,] "foo" "foo" "foo"
[5,] "foo" "foo" "foo"


# Indexing in Matrices

In [62]:
dat <- sample(12)
m <- matrix (dat, ncol = 3)
print (m)

     [,1] [,2] [,3]
[1,]    4    5    7
[2,]    1   10    8
[3,]    6   12    3
[4,]    2   11    9


In [63]:
m[2,3]

[1] 8

In [64]:
m[1:2,3]

[1] 7 8

In [65]:
m[1,]

[1] 4 5 7

In [66]:
m[,3] <-0
print (m)

     [,1] [,2] [,3]
[1,]    4    5    0
[2,]    1   10    0
[3,]    6   12    0
[4,]    2   11    0


In [67]:
m[1:2,2] <- 99
print(m)

     [,1] [,2] [,3]
[1,]    4   99    0
[2,]    1   99    0
[3,]    6   12    0
[4,]    2   11    0


In [68]:
num_rows <- nrow(m)
print (num_rows)

[1] 4


In [70]:
ncol(m)

[1] 3

In [71]:
colMeans(m)

[1]  3.25 55.25  0.00

In [81]:
colSums(m)

[1]  13 221   0

In [74]:
rowSums(m)

[1] 103 100  18  13

# THE DATAFRAME

In [82]:
id <- seq(4)
score <- rnorm(4)
names <- c("john","paul","george","ringo")
vocals <- c(TRUE, TRUE, FALSE, FALSE)
dset <- data.frame(id, names, score, vocals)
print (dset)

  id  names       score vocals
1  1   john  0.04952532   TRUE
2  2   paul  0.67255278   TRUE
3  3 george -0.83726772  FALSE
4  4  ringo  0.67079700  FALSE


In [83]:
dset[1,2]

[1] john
Levels: george john paul ringo

In [84]:
dset$names

[1] john   paul   george ringo 
Levels: george john paul ringo